// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NumberSorter.Data;

#nullable disable

namespace NumberSorter.Data.Migrations
{
    [DbContext(typeof(NumberSorterDBContext))]
    [Migration("20240220230322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NumberSorter.Data.Models.SortedNumbers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InitalValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_values");

                    b.Property<TimeSpan>("SortTime")
                        .HasColumnType("time")
                        .HasColumnName("sort_time");

                    b.Property<string>("SortedValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sorted_values");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sorted_numbers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InitalValues = "[12,23]",
                            SortTime = new TimeSpan(0, 0, 0, 5, 0),
                            SortedValues = "[12,23]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
